name: ShellTestRunner

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # TODO: make a batch of tests that runs on nodetool rather
        #       than the new connectivity mechanism
        otp_version: [24, 25]
        os: [ubuntu-latest] # latest only runs >= 24.2

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'

    - name: Update cabal
      run: cabal update
    - name: Install shelltestrunner
      run: cabal install shelltestrunner-1.9

    - name: Install shellcheck
      run: cabal install ShellCheck

    - name: Run shell tests
      run: shelltests/run_tests.sh
